### ISSUE TITLE
<artifactId>okhttp-spring-boot-autoconfigure</artifactId> not <artifactId>okhttp3-spring-boot-starter</artifactId>

### ISSUE THREAD

**Issue by americanstone** [freefair/okhttp-spring-boot#13]
your read me seems wrong
<dependency>
			<groupId>io.freefair.okhttp-spring-boot</groupId>
			<artifactId>okhttp-spring-boot-autoconfigure</artifactId>
</dependency>
vs 
<dependency>
    <groupId>io.freefair.okhttp-spring-boot</groupId>
    <artifactId>okhttp3-spring-boot-starter</artifactId>
</dependency>

**Comment by larsgrefer** [comment]
What exactly do you mean?

**Comment by americanstone** [comment]
sorry about that.  In your readme Using Maven section.  the artifactId is **okhttp3-spring-boot-starter** but I think it should be **okhttp-spring-boot-autoconfigure**?

**Comment by larsgrefer** [comment]
The default use case is to declare a dependency on the starter. The starter itself depends on the autoconfigure module and a specific okhttp version.
