### ISSUE TITLE
Relase 2.3.10 missing on maven central

### ISSUE THREAD

**Issue by HJK181** [freefair/okhttp-spring-boot#172]
Hi, can you please publish https://github.com/freefair/okhttp-spring-boot/releases/tag/2.3.10 on maven central. Thx. 

Also, 2.3.12 seems to be merged but no release exists ... would be cool to have a release and the artifact on maven central as well.

**Comment by larsgrefer** [comment]
2.3.12 should be available from maven central now

**Comment by HJK181** [comment]
Hi @larsgrefer 
thank you very much fox fixing https://github.com/freefair/okhttp-spring-boot/issues/173 so fast. Unfortunately, I can't find the artifact on maven central yet ... Strangely enough Eclipse does resolve the dependency, but the jar file only contains the META-INF folder, nothing else. But when browsing https://mvnrepository.com/artifact/io.freefair.okhttp-spring-boot/okhttp3-spring-boot-starter no artifact exists ...
