### ISSUE TITLE
请问这个有使用的wiki么

### ISSUE THREAD

**Issue by haoxuexiaoyao** [freefair/okhttp-spring-boot#9]
你好，请问这个整合到spring boot项目里面之后，有使用教程么？
另外这个项目会长期更新么，目前支持的版本是okhttp 3.9.0是么

**Comment by haoxuexiaoyao** [comment]
compile "io.freefair.okhttp-spring-boot:okhttp3-spring-boot-starter:$version" 这个version应该怎么版本号呢

**Comment by Frisch12** [comment]
You can see the latest release version at this page: https://github.com/freefair/okhttp-spring-boot/releases
But consider that you have to add jitpack as a repository to your gradle file.

**Comment by haoxuexiaoyao** [comment]
Thank you!

**Comment by haoxuexiaoyao** [comment]
Excuse me, how to search in the web site?
http://search.maven.org/

**Comment by haoxuexiaoyao** [comment]
How do I use?

**Comment by haoxuexiaoyao** [comment]
I know how to use, I thought it was sealed, this is only in the spring inside the boot configuration okhttp.
